// Matchfile.swift
// Copyright (c) 2021 FastlaneTools

// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced during build time, or when you initialize `match`
//
//  ** NOTE **
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
//

public class Matchfile: MatchfileProtocol {
    
    public var type: String {
        return "appstore"
    }

    public var storageMode: String {
        return "git"
    }
    
    public var appIdentifier: [String] {
        return [ENV.app_identifier.value] + ENV.app_extention_identifiers.listValue
//        return [
//            "com.rework.app",
//            "com.rework.app.extension-share",
//            "com.rework.app.extension-notification",
//            "com.rework.app.extension-spotlight",
//            "com.rework.app.extension-widget-upnext",
//            "com.rework.app.extension-widget-intent"
//        ]
    }
    
    public var gitUrl: String {
        
        return ENV.match_git_url.value
    }
    
    public var username: String? {
        return ENV.apple_id.value
    }
    
    public var teamId: String? {
        return ENV.team_id.value
    }        
}
